name: Wiz Security Scanner
description: Integrates wiz security scanning for infrastructure-as-code and docker images
author: https://github.com/blstrco
requirements:
  - docker
configuration:
  properties:
    image-address:
      type: string
    path:
      type: string
    scan-type:
      type: string
      enum:
        - docker
        - iac
  additionalProperties: false
