#!/bin/bash

set -uxo pipefail

WIZ_DIR="$HOME/.wiz"
SCAN_TYPE="${BUILDKITE_PLUGIN_WIZ_SCAN_TYPE:-}"

if [[ -z "${SCAN_TYPE}" ]]; then
    echo "Missing scan type. Possible values: 'iac', 'docker'"
    exit 1
fi

if [ "${SCAN_TYPE}" = "docker" ] && [[ -z "${BUILDKITE_PLUGIN_WIZ_IMAGE_ADDRESS:-}" ]]; then
    echo "Missing image address, docker scans require an adress to pull the image"
    exit 1
fi

#TODO move this to agent-startup so all agents have wiz setup to save time, possibly directly as cli
setupWiz() {
    echo "Setting up and authenticating wiz"
    mkdir -p $WIZ_DIR
    #TODO wiz-id is public, we should still not have it as hardcoded
    WIZ_API_ID=4augxlyhhnbathv2zkmcbu7djt6jfu4peb6fv5v6in7xcipfkbjhg
    WIZ_API_SECRET=$(aws secretsmanager get-secret-value --secret-id global/buildkite/wiz-api-secret --query "SecretString" --output text)
    docker run \
        --rm -it \
        --mount type=bind,src=$WIZ_DIR,dst=/cli \
        wiziocli.azurecr.io/wizcli:latest-amd64 \
        auth --id=$WIZ_API_ID --secret $WIZ_API_SECRET
}

dockerImageScan() {
    # TODO check feasibility of mount/mountWithLayers
    IMAGE="${BUILDKITE_PLUGIN_WIZ_IMAGE_ADDRESS:-}"
    docker run \
        --rm -it \
        --mount type=bind,src=$WIZ_DIR,dst=/cli,readonly \
        --mount type=bind,src=$PWD,dst=/scan \
        --mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock,readonly \
        wiziocli.azurecr.io/wizcli:latest-amd64 \
        docker scan --image $IMAGE -C \
        --policy-hits-only \
        -f human \
        -o /scan/result,human
    exit_code="$?"
    image_name=$(echo $IMAGE | cut -d "/" -f 2)
    case $exit_code in
    0)
        buildkite-agent annotate "<b>Wiz Docker Image Scan Results</b><br>Name: $image_name<br>Status: Image meets policy requirements " --style 'success' --context 'ctx-success'
        exit 0
        ;;
    *)
        test_result=$(<"$PWD/result")
        buildkite-agent annotate "<b>Wiz Docker Image Scan Results</b><br>Name: $image_name<br>Status: Image doesn't meet policy requirements<br>$test_result" --style 'warning' --context 'ctx-warn'
        exit 1
        ;;
    esac
}

iacScan() {
    cdk synth "cdk.out/*.template.json"
    mkdir -p cloudformation
    #buildkite-agent artifact download "cdk/*.template.json" . --step $BUILDKITE_JOB_ID --build $BUILDKITE_BUILD_ID /cloudformation
    mkdir -p results
    for file in cdk.out/*.template.json; do
        file_name=$(basename "$file")
        docker run \
            --rm -it \
            --mount type=bind,src=$WIZ_DIR,dst=/cli,readonly \
            --mount type=bind,src=$PWD,dst=/scan \
            wiziocli.azurecr.io/wizcli:latest-amd64 \
            iac scan \
            --name $BUILDKITE_JOB_ID -f human -o /scan/results/$file_name,human -C \
            --types 'Cloudformation' \
            --path "/scan/cloudformation/$file"
        exit_code="$?"
        case $exit_code in
        0)
            buildkite-agent annotate 'Wiz: Scanned files meet policy requirements' --style 'success' --context 'ctx-success'
            ;;
        *)
            test_result=$(<"/scan/results/$file_name")
            buildkite-agent annotate "$test_result" --style 'warning' --context 'ctx-warn'
            ;;
        esac
    done
    cd results
    buildkite-agent artifact upload "*.json"
}

case "${SCAN_TYPE}" in
iac)
    setupWiz
    iacScan
    ;;
docker)
    setupWiz
    dockerImageScan
    ;;
esac
