#!/bin/bash

set -euo pipefail

WIZ_DIR="$HOME/.wiz"
SCAN_TYPE="${BUILDKITE_PLUGIN_SCAN_TYPE:-}"

if [[ -z "${SCAN_TYPE}" ]]; then
    echo "Missing scan type. Possible values: 'iac', 'image'"
    exit 1
fi

#TODO move this to agent-startup so all agents have wiz setup to save time, possibly directly as cli
setupWiz() {
    echo "Setting up and authenticating wiz"
    mkdir -p $WIZ_DIR
    #TODO wiz-id is public, we should still not have it as hardcoded
    WIZ_API_ID=4augxlyhhnbathv2zkmcbu7djt6jfu4peb6fv5v6in7xcipfkbjhg
    WIZ_API_SECRET=$(aws secretsmanager get-secret-value --secret-id global/buildkite/wiz-api-secret --query "SecretString" --output text)
    docker run \
        --rm -it \
        --mount type=bind,src=$WIZ_DIR,dst=/cli \
        wiziocli.azurecr.io/wizcli:latest-amd64 \
        auth --id=$WIZ_API_ID --secret $WIZ_API_SECRET
}

imageScan() {
    IMAGE="$BUILDKITE_PLUGIN_IMAGE"
    if [[ -z "${IMAGE}" ]]; then
        echo "Missing value for image. Docker image scanning requires image property."
        exit 1
    fi
    #todo add --driver mountWithLayers?
    docker run \
        --rm -it \
        --mount type=bind,src=$WIZ_DIR,dst=/cli,readonly \
        --mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock,readonly \
        wiziocli.azurecr.io/wizcli:latest-amd64 \
        docker scan --image $IMAGE
}

iacScan() {
    mkdir -p cloudformation
    buildkite-agent artifact download "cdk/*.template.json" . --step $BUILDKITE_JOB_ID --build $BUILDKITE_BUILD_ID /cloudformation
    mkdir -p results
    for file in cloudformation/*.template.json; do
        file_name=$(basename "$file")
        docker run \
            --rm -it \
            --mount type=bind,src=$WIZ_DIR,dst=/cli,readonly \
            --mount type=bind,src=$PWD,dst=/scan \
            wiziocli.azurecr.io/wizcli:latest-amd64 \
            iac scan \
            --name test -f human -o /scan/results/$file_name -C \
            --types 'Cloudformation' \
            --path "/scan/cloudformation/$file"
        exit_code="$?"
        case $exit_code in
        0)
            buildkite-agent annotate 'Wiz: Scanned files meet policy requirements' --style 'success' --context 'ctx-success'
            ;;
        *)
            test_result=$(<"/scan/results/$file_name")
            buildkite-agent annotate "$test_result" --style 'warning' --context 'ctx-warn'
            ;;
        esac
    done
    cd results
    buildkite-agent artifact upload "*.json"
}

case "${SCAN_TYPE}" in
iac)
    setupWiz
    iacScan
    ;;
image)
    setupWiz
    imageScan
    ;;
esac
