#!/bin/bash

set -uxo pipefail

WIZ_DIR="$HOME/.wiz"
SCAN_TYPE="${BUILDKITE_PLUGIN_WIZ_SCAN_TYPE:-}"
CDK_PATH="${BUILDKITE_PLUGIN_WIZ_PATH:-}"

if [[ -z "${SCAN_TYPE}" ]]; then
    echo "Missing scan type. Possible values: 'iac', 'docker'"
    exit 1
fi

if [ "${SCAN_TYPE}" = "docker" ] && [[ -z "${BUILDKITE_PLUGIN_WIZ_IMAGE_ADDRESS:-}" ]]; then
    echo "Missing image address, docker scans require an adress to pull the image"
    exit 1
fi

if [ "${SCAN_TYPE}" = "iac" ] && [[ -z "${BUILDKITE_PLUGIN_WIZ_PATH:-}" ]]; then
    echo "Missing cdk.out path, IaC scans require a path with the cloudformation files"
    exit 1
fi

#TODO move this to agent-startup so all agents have wiz setup to save time, possibly directly as cli
setupWiz() {
    echo "Setting up and authenticating wiz"
    mkdir -p $WIZ_DIR
    #TODO wiz-id is public, we should still not have it as hardcoded
    WIZ_API_ID=4augxlyhhnbathv2zkmcbu7djt6jfu4peb6fv5v6in7xcipfkbjhg
    WIZ_API_SECRET=$(aws secretsmanager get-secret-value --secret-id global/buildkite/wiz-api-secret --query "SecretString" --output text)
    docker run \
        --rm -it \
        --mount type=bind,src=$WIZ_DIR,dst=/cli \
        wiziocli.azurecr.io/wizcli:latest-amd64 \
        auth --id=$WIZ_API_ID --secret $WIZ_API_SECRET
}

dockerImageScan() {
    # TODO check feasibility of mount/mountWithLayers
    IMAGE="${BUILDKITE_PLUGIN_WIZ_IMAGE_ADDRESS:-}"
    # make sure local docker has the image
    docker pull $IMAGE
    docker run \
        --rm -it \
        --mount type=bind,src=$WIZ_DIR,dst=/cli,readonly \
        --mount type=bind,src=$PWD,dst=/scan \
        --mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock,readonly \
        wiziocli.azurecr.io/wizcli:latest-amd64 \
        docker scan --image $IMAGE \
        --policy-hits-only \
        -f human \
        -o /scan/result,human,true
    exit_code="$?"
    image_name=$(echo $IMAGE | cut -d "/" -f 2)
    # FIXME: Linktree Specific Env. Var.
    USE_BUILDKITE_ARTIFACT_BUCKET="true" buildkite-agent artifact upload $PWD/result --log-level info
    case $exit_code in
    7)
        buildkite-agent annotate --append "<b>Wiz Docker Image Scan for $image_name meets policy requirements " --style 'success' --context 'ctx-wiz-docker-success'
        exit 0
        ;;
    *)
        cat <<EOF >> ./wiz-docker-scan-annotation.md
<details>
<summary>Wiz Docker Image Scan for $image_name does not meet policy requirements.</summary>

\`\`\`term
$(cat $PWD/result)
\`\`\`

</details>
EOF
        printf '%b\n' "$(cat ./wiz-docker-scan-annotation.md)" | buildkite-agent annotate --append --context 'ctx-wiz-docker-warning' --style 'warning'
        exit 0
        ;;
    esac
}

iacScan() {
    mkdir -p results
    for file in ${CDK_PATH}/*.template.json; do
        file_name=$(basename "$file")
        job_name="${file_name}-${BUILDKITE_JOB_ID}"
        docker run \
            --rm -it \
            --mount type=bind,src=$WIZ_DIR,dst=/cli,readonly \
            --mount type=bind,src=$PWD,dst=/scan \
            wiziocli.azurecr.io/wizcli:latest-amd64 \
            iac scan \
            --name $BUILDKITE_JOB_ID -f human -o /scan/results/$file_name,human \
            --types 'Cloudformation' \
            --path "/scan/$file"
        exit_code="$?"
        case $exit_code in
        7)
            buildkite-agent annotate --append --context 'ctx-wiz-iac-success' --style 'success' "<b>Wiz IaC Scan Results for $job_name meets policy requirements"
            ;;
        *)
        cat <<EOF >> ./wiz-iac-scan-annotation.md
<details>
<summary>Wiz IaC Scan Results for $job_name does not meet policy requirements.</summary>

\`\`\`term
$(cat results/$file_name)
\`\`\`

</details>
EOF
        printf '%b\n' "$(cat ./wiz-iac-scan-annotation.md)" | buildkite-agent annotate --append --context 'ctx-wiz-iac-warning' --style 'warning'
        ;;
        esac
    done
    buildkite-agent artifact upload "results/**/*" --log-level info
}

case "${SCAN_TYPE}" in
iac)
    setupWiz
    iacScan
    ;;
docker)
    setupWiz
    dockerImageScan
    ;;
esac
